# list of application_ids and associated model_architectures

- application_id: 0
  model_architecture: bloom-176b
  model_size: bloom-176b-fp16
  #model_architecture: llama2-70b
  #model_size: llama2-70b-fp16
  allocator: noop
  scheduler: round_robin
  overheads: {}
  debug: ${debug}
  _target_: application.Application
