_target_: scheduler.KVRoundRobinScheduler
overheads: {}
executor_overheads:
  submit_task: 0
  submit_flow: 0
  finish_request: 0
prompt_processors: ["h100-80gb"]
token_processors: ["a100-80gb"]
transfer_bandwidth: 200
