_target_: scheduler.MixedPoolScheduler
overheads: {}
executor_overheads:
  submit_task: 0
  submit_flow: 0
  finish_request: 0
prompt_processors: ["h100-80gb"]
token_processors: ["a100-80gb"]
prompt_max_pending_batch_tokens: 8192
token_max_pending_batch_tokens: 2048
transfer_bandwidth: 200
